-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 11:39:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dating_c04
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dating_c04
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dating_c04` DEFAULT CHARACTER SET utf8 ;
USE `dating_c04` ;

-- -----------------------------------------------------
-- Table `dating_c04`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`type_user` (
  `id_type_user` INT NOT NULL AUTO_INCREMENT,
  `type_user_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `job` VARCHAR(45) NULL,
  `married` BIT(1) NULL,
  `avatar` VARCHAR(255) NULL,
  `join_day` DATE NOT NULL,
  `coin` INT NOT NULL,
  `id_type_user` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_type_user`),
  INDEX `fk_user_type_user1_idx` (`id_type_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_type_user1`
    FOREIGN KEY (`id_type_user`)
    REFERENCES `dating_c04`.`type_user` (`id_type_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` INT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id_account`),
  INDEX `fk_account_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`account_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`account_role` (
  `id_account` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_account`, `id_role`),
  INDEX `fk_account_has_role_role1_idx` (`id_role` ASC) VISIBLE,
  INDEX `fk_account_has_role_account1_idx` (`id_account` ASC) VISIBLE,
  CONSTRAINT `fk_account_has_role_account1`
    FOREIGN KEY (`id_account`)
    REFERENCES `dating_c04`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_has_role_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `dating_c04`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`hobbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`hobbit` (
  `id_hobbit` INT NOT NULL AUTO_INCREMENT,
  `hobbit_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hobbit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`user_has_hobbit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`user_has_hobbit` (
  `id_user` INT NOT NULL,
  `id_hobbit` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_hobbit`),
  INDEX `fk_user_has_hobbit_hobbit1_idx` (`id_hobbit` ASC) VISIBLE,
  INDEX `fk_user_has_hobbit_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_hobbit_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_hobbit_hobbit1`
    FOREIGN KEY (`id_hobbit`)
    REFERENCES `dating_c04`.`hobbit` (`id_hobbit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `media` TEXT NULL,
  `time` DATETIME NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`, `id_user`),
  INDEX `fk_post_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `id_post` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `id_post`, `id_user`),
  INDEX `fk_comment_post1_idx` (`id_post` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `dating_c04`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`target` (
  `id_target` INT NOT NULL AUTO_INCREMENT,
  `target_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_target`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`user_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`user_target` (
  `id_user` INT NOT NULL,
  `id_target` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_target`),
  INDEX `fk_user_has_target_target1_idx` (`id_target` ASC) VISIBLE,
  INDEX `fk_user_has_target_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_target_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_target_target1`
    FOREIGN KEY (`id_target`)
    REFERENCES `dating_c04`.`target` (`id_target`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`invoice` (
  `id_invoice` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_invoice`, `id_user`),
  INDEX `fk_invoice_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`friend_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`friend_list` (
  `id_friend_list` INT NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL,
  `id_user1` INT NOT NULL,
  `id_user2` INT NOT NULL,
  PRIMARY KEY (`id_friend_list`, `id_user1`, `id_user2`),
  INDEX `fk_friend_list_user1_idx` (`id_user1` ASC) VISIBLE,
  INDEX `fk_friend_list_user2_idx` (`id_user2` ASC) VISIBLE,
  CONSTRAINT `fk_friend_list_user1`
    FOREIGN KEY (`id_user1`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_list_user2`
    FOREIGN KEY (`id_user2`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`report` (
  `id_report` INT NOT NULL AUTO_INCREMENT,
  `name_report` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_report`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`report_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`report_user` (
  `id_report` INT NOT NULL,
  `id_reported` INT NOT NULL,
  `id_reporter` INT NOT NULL,
  `status` INT NOT NULL,
  `time_report` DATETIME NOT NULL,
  PRIMARY KEY (`id_report`, `id_reported`, `id_reporter`),
  INDEX `fk_report_has_user_user1_idx` (`id_reported` ASC) VISIBLE,
  INDEX `fk_report_has_user_report1_idx` (`id_report` ASC) VISIBLE,
  INDEX `fk_report_user_user1_idx` (`id_reporter` ASC) VISIBLE,
  CONSTRAINT `fk_report_has_user_report1`
    FOREIGN KEY (`id_report`)
    REFERENCES `dating_c04`.`report` (`id_report`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_has_user_user1`
    FOREIGN KEY (`id_reported`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_user_user1`
    FOREIGN KEY (`id_reporter`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`gift` (
  `id_gift` INT NOT NULL AUTO_INCREMENT,
  `gift_name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id_gift`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`gift_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`gift_user` (
  `gift_id_gift` INT NOT NULL,
  `id_user_sender` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`gift_id_gift`, `id_user_sender`, `user_id_user`),
  INDEX `fk_gift_has_user_user1_idx` (`id_user_sender` ASC) VISIBLE,
  INDEX `fk_gift_has_user_gift1_idx` (`gift_id_gift` ASC) VISIBLE,
  INDEX `fk_gift_has_user_user2_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_gift_has_user_gift1`
    FOREIGN KEY (`gift_id_gift`)
    REFERENCES `dating_c04`.`gift` (`id_gift`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_has_user_user1`
    FOREIGN KEY (`id_user_sender`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_has_user_user2`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`room_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`room_chat` (
  `id_room_chat` INT NOT NULL AUTO_INCREMENT,
  `name_room_chat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_room_chat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`room_chat_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`room_chat_user` (
  `id_room_chat` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_room_chat`, `id_user`),
  INDEX `fk_room_chat_has_user_user1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_room_chat_has_user_room_chat1_idx` (`id_room_chat` ASC) VISIBLE,
  CONSTRAINT `fk_room_chat_has_user_room_chat1`
    FOREIGN KEY (`id_room_chat`)
    REFERENCES `dating_c04`.`room_chat` (`id_room_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_chat_has_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dating_c04`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dating_c04`.`message` (
  `id_room_chat` INT NOT NULL,
  `id_user` INT NOT NULL,
  `message` TEXT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_room_chat`, `id_user`),
  INDEX `fk_room_chat_has_user_user2_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_room_chat_has_user_room_chat2_idx` (`id_room_chat` ASC) VISIBLE,
  CONSTRAINT `fk_room_chat_has_user_room_chat2`
    FOREIGN KEY (`id_room_chat`)
    REFERENCES `dating_c04`.`room_chat` (`id_room_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_chat_has_user_user2`
    FOREIGN KEY (`id_user`)
    REFERENCES `dating_c04`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
